name: hello_world
on: push
jobs:
  build:
    name: hello
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World Self runner Docker"
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
